package com.learnup.db.model;

import io.qameta.allure.Severity;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Categories {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column categories.id
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column categories.title
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private String title;
}