package com.learnup.db.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.title
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category_id
     *
     * @mbg.generated Tue Dec 14 07:58:58 CET 2021
     */
    private Long category_id;

}